/**
 * ADK UI — componentes Vue 3 + TypeScript + Tailwind (tokens --adk-*).
 * Fuente de la verdad: Figma › [ADK] Design System. Docs: ADK/components/*.md
 */
export { default as AdkAlert } from './components/AdkAlert.vue'
export { default as AdkAttractScreen } from './components/AdkAttractScreen.vue'
export { default as AdkBadge } from './components/AdkBadge.vue'
export { default as AdkBanner } from './components/AdkBanner.vue'
export { default as AdkButton } from './components/AdkButton.vue'
export { default as AdkCartBar } from './components/AdkCartBar.vue'
export { default as AdkCartItem } from './components/AdkCartItem.vue'
export { default as AdkCategoryCard } from './components/AdkCategoryCard.vue'
export { default as AdkCategoryNavButton } from './components/AdkCategoryNavButton.vue'
export { default as AdkChip } from './components/AdkChip.vue'
export { default as AdkDropdown } from './components/AdkDropdown.vue'
export { default as AdkFooter } from './components/AdkFooter.vue'
export { default as AdkHeader } from './components/AdkHeader.vue'
export { default as AdkIllustrationButton } from './components/AdkIllustrationButton.vue'
export { default as AdkKeyboard } from './components/AdkKeyboard.vue'
export { default as AdkKioskShell } from './components/AdkKioskShell.vue'
export { default as AdkLoader } from './components/AdkLoader.vue'
export { default as AdkLogo } from './components/AdkLogo.vue'
export { default as AdkLoyaltyPill } from './components/AdkLoyaltyPill.vue'
export { default as AdkNavButton } from './components/AdkNavButton.vue'
export { default as AdkNavMenu } from './components/AdkNavMenu.vue'
export { default as AdkPointsHint } from './components/AdkPointsHint.vue'
export { default as AdkProductCard } from './components/AdkProductCard.vue'
export { default as AdkProductCustomRow } from './components/AdkProductCustomRow.vue'
export { default as AdkProgressSteps } from './components/AdkProgressSteps.vue'
export { default as AdkQuantity } from './components/AdkQuantity.vue'
export { default as AdkScrollArea } from './components/AdkScrollArea.vue'
export { default as AdkSizeSelector } from './components/AdkSizeSelector.vue'
export { default as AdkSnackbar } from './components/AdkSnackbar.vue'
export { default as AdkSnackbarHost } from './components/AdkSnackbarHost.vue'
export { default as AdkTextField } from './components/AdkTextField.vue'
export { default as AdkToggle } from './components/AdkToggle.vue'
export { default as AdkUserFooter } from './components/AdkUserFooter.vue'
export { default as AdkUserPoints } from './components/AdkUserPoints.vue'

export { useSnackbar, type AdkSnackbarItem } from './composables/useSnackbar'
export type { AdkButtonSize, AdkButtonVariant } from './components/AdkButton.vue'
export type { AdkBadgeType } from './components/AdkBadge.vue'
export type { AdkCartPart } from './components/AdkCartItem.vue'
export type { AdkNavItem } from './components/AdkNavMenu.vue'
export type { AdkOption } from './components/AdkDropdown.vue'
export type { AdkSizeOption } from './components/AdkSizeSelector.vue'
export type { AdkSnackbarStatus } from './components/AdkSnackbar.vue'
export type { AdkStep, AdkStepState } from './components/AdkProgressSteps.vue'
export type { AdkUserFooterVariant } from './components/AdkUserFooter.vue'
